# Generated by Django 4.2 on 2023-07-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=10000)),
                ('content', models.TextField(max_length=10000)),
                ('case', models.BooleanField(blank=True, default=True)),
                ('first_key', models.BooleanField(blank=True, default=False)),
                ('all_keys', models.BooleanField(blank=True, default=True)),
                ('many_keys', models.DecimalField(blank=True, decimal_places=0, max_digits=10000, null=True)),
            ],
        ),
    ]
