# Generated by Django 4.2 on 2023-07-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_many_keys_filter_num_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='all_keys',
            new_name='find_all',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='first_key',
            new_name='find_first',
        ),
    ]
