# Generated by Django 4.2 on 2023-07-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_all_keys_filter_find_all_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='find_all',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='find_first',
        ),
        migrations.AddField(
            model_name='filter',
            name='search',
            field=models.CharField(blank=True, default='findall', max_length=128, null=True),
        ),
    ]
