# Generated by Django 4.2 on 2023-07-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_filter_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='search',
            field=models.CharField(choices=[('search_all', 'search for all'), ('search_first', 'search for first'), ('custom_search', 'custom search')], default='search_first', max_length=128, null=True),
        ),
    ]
