# Generated by Django 4.2 on 2023-08-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_filter_num_keys_alter_filter_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='num_keys',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10000, null=True),
        ),
    ]
