# Generated by Django 4.2 on 2023-08-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_filter_num_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='search',
            field=models.CharField(choices=[('search_all', 'search for all'), ('search_first', 'search for first'), ('search_last', 'search for last'), ('custom_search', 'custom search')], default='search_all', max_length=128, null=True),
        ),
    ]
