# Generated by Django 4.2 on 2023-08-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_filter_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
