# Generated by Django 4.2 on 2023-08-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_filter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
